services:

  redis:
    image: valkey/valkey:8-alpine
    container_name: searxng-redis
    restart: unless-stopped

    networks:
      - internal

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped

    environment:
      SEARXNG_BASE_URL: https://search.devlooper.co.in/
      UWSGI_THREADS: 4
      UWSGI_WORKERS: 4

    volumes:
      - ./searxng:/etc/searxng

    depends_on:
      - redis

    networks:
      - internal
      - traefik-public

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public

      - traefik.http.routers.searxng.rule=Host(`search.devlooper.co.in`)
      - traefik.http.routers.searxng.entrypoints=web

      - traefik.http.services.searxng.loadbalancer.server.port=8080

    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:8080" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:

  internal:
    external: true

  traefik-public:
    external: true
